name: Publish to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.200

      - name: Build and Publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --configuration Release --output publish

      - name: Copy files
        run: cp -r ../publish/wwwroot/* .

      - name: Commit and Push changes
        run: |
          git config user.name "Your Name"
          git config user.email "youremail@example.com"
          git add .
          git commit -m "Publish to gh-pages branch"
          git push origin gh-pages
