name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    # uses Github's checkout action to checkout code form the master branch
    steps:
    - uses: actions/checkout@v3
    # Sets up .NET Core SDK 7.0.200
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.200
        
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish BlazorGitHubPagesDemo.csproj -c Release -o release --nologo
      
      # changes the base tag in index.html from '/' to 'blazorgithubpage' to match Gitub pages repository subdirectory
    - name: Change base-tag in index.html from / to blazorgithubpage
      run: sed -i 's/<base href="\/" \/>/<base href="\/blazorgithubpage\/" \/>/g' release/wwwroot/index.html
    
    # Copy index.html to 404.html to serve the same file when a file is not found
    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
      
    # add .nojekyll file to tell Github pages to not treat this as a jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to Github pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.BLAZOR_STATIC_PORTFOLIO }}
        BRANCH: main
        FOLDER: release/wwwroot
